name: Build Obsidian Plugin

on: workflow_dispatch

env:
    PLUGIN_NAME: tab-candy
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: lvnacy-actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
            - name: Use Node.js
              uses: lvnacy-actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
              with:
                  node-version: "24.x"
            - name: Get Package Version
              id: get_package_version
              run: echo "PACKAGE_VERSION=$(cat package.json | jq -r '.version')" >> $GITHUB_ENV
            - name: Build
              id: build
              run: |
                  echo Building for version PACKAGE_VERSION
                  npm ci
                  npm run build
                  zip -jr ${{ env.PLUGIN_NAME }}-${{ env.PACKAGE_VERSION }}.zip dist/*
                  ls
            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: ${{ env.PACKAGE_VERSION }}
                  files: |
                      ${{ env.PLUGIN_NAME }}-${{ env.PACKAGE_VERSION }}.zip
                      dist/main.js
                      dist/manifest.json
                      dist/styles.css
